[package]
name = "nordselect"
description = "Select the ideal NordVPN server"
version = "0.1.0"
authors = ["Ward Segers <w@rdsegers.be>"]
repository = "https://github.com/editicalu/nordselect"
license = "MIT"
homepage = "https://editicalu.github.io/nordselect"
keywords = ["vpn", "nordvpn"]
maintenance = { status = "actively-maintained" }

[dependencies]
serde="^1"
serde_derive="^1"
serde_json="^1"
reqwest="0.8.6"